export const PERMISSIONS = [
  'dashboard:read',
  'products:read',
  'products:write',
  'categories:read',
  'categories:write',
  'suppliers:read',
  'suppliers:write',
  'stock:read',
  'stock:write',
  'movements:read',
  'movements:write',
  'purchases:read',
  'purchases:write',
  'reports:read',
  'reports:export',
  'users:read',
  'users:write',
  'settings:read',
  'settings:write',
  'audit:read',
  'backup:write',
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  ADMIN: [...PERMISSIONS],
  GERENTE: [
    'dashboard:read',
    'products:read',
    'products:write',
    'categories:read',
    'categories:write',
    'suppliers:read',
    'suppliers:write',
    'stock:read',
    'stock:write',
    'movements:read',
    'movements:write',
    'purchases:read',
    'purchases:write',
    'reports:read',
    'reports:export',
    'users:read',
    'settings:read',
    'audit:read',
  ],
  ESTOQUISTA: [
    'dashboard:read',
    'products:read',
    'products:write',
    'categories:read',
    'suppliers:read',
    'stock:read',
    'stock:write',
    'movements:read',
    'movements:write',
    'purchases:read',
    'purchases:write',
    'reports:read',
    'reports:export',
  ],
  FUNCIONARIO: [
    'dashboard:read',
    'products:read',
    'stock:read',
    'movements:read',
    'movements:write',
  ],
};
